language: c
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    packages:
      - gfortran
      - scons
script:
  - scons test
  - ./test-udsp
  - scons test --clean
  - export CFLAGS="-coverage -g -O0 $CFLAGS"
  - export LDFLAGS="-coverage $LDFLAGS"
  - scons test
  - ./test-udsp
  - gcov udsp.c
after_success:
  - bash <(curl -s https://codecov.io/bash) -g './test-*'
