language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y gfortran scons
script:
  - scons --clean
  - scons
  - scons test
  - ./test-udsp
compiler:
  - clang
  - gcc
