language: c
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    packages:
      - gfortran
      - scons
script:
  - scons all
  - scons check
after_success:
  - export CFLAGS="-coverage -g -O0 $CFLAGS"
  - export LDFLAGS="-coverage $LDFLAGS"
  - scons check
  - gcov udsp.c
  - bash <(curl -s https://codecov.io/bash) -g './test-*'
